#!/bin/bash
#######
# HEADER FROM source /code/pybombs/default/setup_env.sh
# WARNING: This file is auto-generated by pybombs, any manual changes to it may be overwritten!
export PATH="/code/pybombs/default/bin:$PATH"
export PYTHONPATH="/code/pybombs/default/python:/code/pybombs/default/lib/python2.6/site-packages:/code/pybombs/default/lib64/python2.6/site-packages:/code/pybombs/default/lib/python2.6/dist-packages:/code/pybombs/default/lib64/python2.6/dist-packages:/code/pybombs/default/lib/python2.7/site-packages:/code/pybombs/default/lib64/python2.7/site-packages:/code/pybombs/default/lib/python2.7/dist-packages:/code/pybombs/default/lib64/python2.7/dist-packages:$PYTHONPATH"
export LD_LIBRARY_PATH="/code/pybombs/default/lib:/code/pybombs/default/lib64/:$LD_LIBRARY_PATH"
export LIBRARY_PATH="/code/pybombs/default/lib:/code/pybombs/default/lib64/:$LIBRARY_PATH"
export PKG_CONFIG_PATH="/code/pybombs/default/lib/pkgconfig:/code/pybombs/default/lib64/pkgconfig:$PKG_CONFIG_PATH"
export PYBOMBS_PREFIX="/code/pybombs/default"
# If we're in a Python virtualenv, activate that
if [ -r /code/pybombs/default/bin/activate ]; then
    source /code/pybombs/default/bin/activate
fi

######## 
# stat -c "%n %s" /tmp/gs-sample.wav
./python/afsk_csu.py
# stat -c "%n %s" /tmp/gs-sample.binary
./python/afsk_bin2hex.py